apiVersion: v1
kind: Pod
metadata:
   name: nginxpod
spec:
  containers:
    - image: nginx
      name: nginxcontainer
      ports:
        - containerPort: 80
      volumeMounts:
         - name: myconfigvolume
           mountPath: /etc/nginx/conf.d/
  volumes:
    - name: myconfigvolume
      configMap:
         name: mynginxconf
